### ISSUE TITLE
개발 진행 여부

### ISSUE THREAD

**Issue by somehowko** [dldisud/hanspell-plugin#1]
현재 중단 상태인 것 같은데 혹시 계속 개발하실 생각은 없으신가요?

**Comment by dldisud** [comment]
따로 다 만들어 둔게 있긴 합니다.
어느 정도 성능의 제약이 있긴 하지만 원하시면 공개 해드리 겠습니다.
아마 웹연갤에서 오셨죠?

**Comment by dldisud** [comment]
https://github.com/dldisud/obsidian-korean-spellchecker

얘가 수정판으로 UI나 기능면에서 여러모로 수정된 상태입니다

**Comment by somehowko** [comment]
앗 감사드립니다. 아뇨, 옵시디언 hanspell을 검색하다 여기까지 왔습니다. 

hanspell 버전은 제가 잘 못 이해하고 있었던 것 같습니다. 폴더가 아니라 -g 글로벌 설치로 해놓고 왜 hanspell이 로딩되지 않는지 헤메고 있었네요..


해당 버전은 잘  사용하고 있습니다! 
Hanspell 버전을 기대했던게 vscode-hanspell 에서는 실시간 오탈자 검색이 가능한 것 같더라구요, 그래서 이 기능을 옵시디언에 넣을 수 있지 않을까 생각했습니다.
혹시 추후에 obsidian-langaugetool 플러그인 처럼 실시간 맞춤법 검사 (오류시 빨간색으로 뜨고 클릭 -> 수정 ) 기능을 추가하실 생각은 없으실까요...? 

행복한 주말 보내세요!
